import { nothing } from 'lit';
import '@material/web/icon/icon.js';
import '@material/web/checkbox/checkbox.js';
import '@material/web/button/outlined-button.js';
import '@material/web/button/filled-button.js';
import '@material/web/button/elevated-button.js';
import '@material/web/textfield/filled-text-field.js';
import '@material/web/progress/circular-progress.js';
import '@yrpri/webapp/common/yp-image.js';
import { BaseChatBotServerApi } from './BaseChatBotApi.js';
import { YpBaseElement } from '@yrpri/webapp/common/yp-base-element.js';
export declare class PsAiChatElement extends YpBaseElement {
    message: string;
    wsMessage: PsAiChatWsMessage;
    updateMessage: string;
    sender: 'you' | 'bot';
    detectedLanguage: string;
    clusterId: number;
    type: 'start' | 'error' | 'moderation_error' | 'info' | 'welcomeMessage' | 'message' | 'thinking' | 'noStreaming' | undefined;
    spinnerActive: boolean;
    fullReferencesOpen: boolean;
    followUpQuestionsRaw: string;
    followUpQuestions: string[];
    jsonLoading: boolean;
    api: BaseChatBotServerApi;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    stopJsonLoading(): void;
    handleJsonLoadingStart: () => void;
    handleJsonLoadingEnd: (event: any) => void;
    static get styles(): any[];
    get isError(): boolean;
    renderCGImage(): import("lit").TemplateResult<1>;
    renderRoboImage(): import("lit").TemplateResult<1>;
    renderJson(): import("lit").TemplateResult<1>;
    renderInfo(): import("lit").TemplateResult<1> | typeof nothing;
    shortenText(text: string, maxLength: number): string;
    capitalizeFirstLetter(text: string): string;
    stripDomainForFacIcon(url: string): string;
    renderChatGPT(): any;
    parseFollowUpQuestions(): void;
    updated(changedProperties: Map<string | number | symbol, unknown>): void;
    renderUser(): any;
    renderNoStreaming(): import("lit").TemplateResult<1>;
    renderThinking(): import("lit").TemplateResult<1>;
    getThinkingText(): "Mõeldes..." | "Hugsa..." | "Thinking...";
    renderMessage(): any;
    render(): import("lit").TemplateResult<1>;
}
//# sourceMappingURL=ps-ai-chat-element.d.ts.map