import { Job } from "bullmq";
import { Base } from "../base.js";
export declare abstract class BaseAgent extends Base {
    job: Job;
    getRedisKey(groupId: number): string;
    abstract initializeMemory(job: Job): Promise<void>;
    abstract process(): Promise<void>;
    setup(job: Job): Promise<void>;
    defaultStages: {
        "create-root-causes-search-queries": {};
        "web-search-root-causes": {};
        "web-get-root-causes-pages": {};
        "rank-web-root-causes": {};
        "rate-web-root-causes": {};
        "web-get-refined-root-causes": {};
        "get-metadata-for-top-root-causes": {};
        "create-sub-problems": {};
        "rank-sub-problems": {};
        "reduce-sub-problems": {};
        "create-entities": {};
        "rank-entities": {};
        "create-search-queries": {};
        "rank-root-causes-search-results": {};
        "rank-root-causes-search-queries": {};
        "create-sub-problem-images": {};
        "rank-search-queries": {};
        "web-search": {};
        "rate-solutions": {};
        "rank-search-results": {};
        "rank-web-solutions": {};
        "web-get-pages": {};
        "create-seed-solutions": {};
        "create-pros-cons": {};
        "create-solution-images": {};
        "create-problem-statement-image": {};
        "rank-pros-cons": {};
        "rank-solutions": {};
        "group-solutions": {};
        "evolve-create-population": {};
        "evolve-mutate-population": {};
        "evolve-recombine-population": {};
        "evolve-reap-population": {};
        "topic-map-solutions": {};
        "evolve-rank-population": {};
        "analyse-external-solutions": {};
        "policies-seed": {};
        "policies-create-images": {};
        "create-evidence-search-queries": {};
        "web-get-evidence-pages": {};
        "web-search-evidence": {};
        "rank-web-evidence": {};
        "rate-web-evidence": {};
        "web-get-refined-evidence": {};
        "get-metadata-for-top-evidence": {};
        "validation-agent": {};
    };
    saveMemory(): Promise<void>;
}
//# sourceMappingURL=baseAgent.d.ts.map