import { BaseChatModel } from "../aiModels/baseChatModel.js";
import { PsAgent } from "../dbModels/agent.js";
import { PolicySynthBaseAgent } from "./agent.js";
import { PsAiModelSize, PsAiModelType } from "../aiModelTypes.js";
export declare abstract class PolicySynthOperationsAgent extends PolicySynthBaseAgent {
    memory: PsAgentMemoryData;
    agent: PsAgent;
    models: Map<string, BaseChatModel>;
    modelsByType: Map<PsAiModelType, BaseChatModel>;
    skipAiModels: boolean;
    modelIds: Map<string, number>;
    modelIdsByType: Map<PsAiModelType, number>;
    limitedLLMmaxRetryCount: number;
    mainLLMmaxRetryCount: number;
    maxModelTokensOut: number;
    modelTemperature: number;
    startProgress: number;
    endProgress: number;
    rateLimits: PsModelRateLimitTracking;
    constructor(agent: PsAgent, memory: PsAgentMemoryData | undefined, startProgress: number, endProgress: number);
    process(): Promise<void>;
    loadAgentMemoryFromRedis(): Promise<void>;
    initializeModels(): Promise<void>;
    callModel(modelType: PsAiModelType, modelSize: PsAiModelSize, messages: PsModelMessage[], parseJson?: boolean, limitedRetries?: boolean, tokenOutEstimate?: number, streamingCallbacks?: Function): Promise<any>;
    callTextModel(modelSize: PsAiModelSize, messages: PsModelMessage[], parseJson?: boolean, limitedRetries?: boolean, tokenOutEstimate?: number, streamingCallbacks?: Function): Promise<any>;
    callEmbeddingModel(messages: PsModelMessage[]): Promise<null>;
    callMultiModalModel(messages: PsModelMessage[]): Promise<null>;
    callAudioModel(messages: PsModelMessage[]): Promise<null>;
    callVideoModel(messages: PsModelMessage[]): Promise<null>;
    callImageModel(messages: PsModelMessage[]): Promise<null>;
    saveTokenUsage(modelType: PsAiModelType, modelSize: PsAiModelSize, tokensIn: number, tokensOut: number): Promise<void>;
    formatNumber(number: number, fractions?: number): string;
    updateRangedProgress(progress: number | undefined, message: string): Promise<void>;
    updateProgress(progress: number | undefined, message: string): Promise<void>;
    saveMemory(): Promise<void>;
    getConfigOld<T>(uniqueId: string, defaultValue: T): T;
    getTokensFromMessages(messages: PsModelMessage[]): Promise<number>;
    getConfig<T>(uniqueId: string, defaultValue: T): T;
}
//# sourceMappingURL=operationsAgent.d.ts.map