import winston from "winston";
import { ChatOpenAI } from "@langchain/openai";
import { BaseMessage } from "@langchain/core/messages";
import { Callbacks } from "@langchain/core/callbacks/manager";
export declare class PolicySynthAgentBase {
    memory?: PsBaseMemoryData;
    logger: winston.Logger;
    timeStart: number;
    chat: ChatOpenAI | undefined;
    private rateLimits;
    constructor(memory?: PsBaseMemoryData | undefined);
    static get emptyDefaultStages(): {
        "create-root-causes-search-queries": {};
        "web-search-root-causes": {};
        "web-get-root-causes-pages": {};
        "rank-web-root-causes": {};
        "rate-web-root-causes": {};
        "web-get-refined-root-causes": {};
        "get-metadata-for-top-root-causes": {};
        "create-problem-statement-image": {};
        "create-sub-problems": {};
        "rank-sub-problems": {};
        "policies-seed": {};
        "policies-create-images": {};
        "create-entities": {};
        "rank-entities": {};
        "reduce-sub-problems": {};
        "create-search-queries": {};
        "rank-root-causes-search-results": {};
        "rank-root-causes-search-queries": {};
        "create-sub-problem-images": {};
        "rank-search-queries": {};
        "web-search": {};
        "dedup-web-solutions": {};
        "rank-web-solutions": {};
        "rate-solutions": {};
        "rank-search-results": {};
        "web-get-pages": {};
        "create-seed-solutions": {};
        "create-pros-cons": {};
        "create-solution-images": {};
        "rank-pros-cons": {};
        "rank-solutions": {};
        "group-solutions": {};
        "evolve-create-population": {};
        "evolve-mutate-population": {};
        "evolve-recombine-population": {};
        "evolve-reap-population": {};
        "topic-map-solutions": {};
        "evolve-rank-population": {};
        "analyse-external-solutions": {};
        "create-evidence-search-queries": {};
        "web-get-evidence-pages": {};
        "web-search-evidence": {};
        "rank-web-evidence": {};
        "rate-web-evidence": {};
        "web-get-refined-evidence": {};
        "get-metadata-for-top-evidence": {};
        "validation-agent": {};
        "ingestion-agent": {};
        "engineering-agent": {};
    };
    getJsonBlock(text: string): string;
    get fullLLMCostsForMemory(): number | undefined;
    private repairJson;
    private parseJsonResponse;
    callLLM(stage: PsMemoryStageTypes, modelConstants: PsBaseAIModelConstants, messages: BaseMessage[], parseJson?: boolean, limitedRetries?: boolean, tokenOutEstimate?: number, streamingCallbacks?: Callbacks): Promise<any>;
    private updateRateLimits;
    private checkRateLimits;
    private addRequestTimestamp;
    private addTokenEntry;
    private slideWindowForRequests;
    private slideWindowForTokens;
    private getTokensFromMessages;
    private updateMemoryStages;
    formatNumber(number: number, fractions?: number): string;
    saveMemory(): Promise<void>;
}
//# sourceMappingURL=baseAgent.d.ts.map